### ISSUE TITLE
Ports are not accessible

### ISSUE THREAD

**Issue by rkesters** [apocas/dockerode-compose#11]
When using the below compose file, the service is not reachable on the defined port. However when I use docker-compose the service is reachable.

```
version: '3'
services:
    wiremock:
        image: 'holomekc/wiremock-gui:latest'
        container_name: my_wiremock
        ports:
            - '8088:8080'
        volumes:
            - 'wmdata:/home/wiremock/storage'
        environment:
            WIREMOCK_OPTIONS: '--max-request-journal=1000,--local-response-templating,--root-dir=/home/wiremock/storage'
```

Any thoughts, to why.
