### ISSUE TITLE
"/" can't be used  in volume

### ISSUE THREAD

**Issue by humiyan02** [apocas/dockerode-compose#23]
When I compose up, below error occur.
```
Error: (HTTP code 400) unexpected - create wordpress_./myTheme: "wordpress_./myTheme" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path 
```
Perhaps, "/" can't  be used in local volume string.

docker-compose.yml
```
version: "3.9"
    
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes_from:
      - db:ro
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WP_ENVIRONMENT_TYPE: local
    volumes:
      - ./myTheme:/var/www/html/wp-content/themes/myTheme
volumes:
  db_data: {}
  wordpress_data: {}

```
