### ISSUE TITLE
Support process.env

### ISSUE THREAD

**Issue by humiyan02** [apocas/dockerode-compose#24]
I want to use process.env for port mapping.

```
version: '3.9'

services:
  wordpress_with_theme_db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress_with_theme_wordpress:
    depends_on:
      - wordpress_with_theme_db
    image: wordpress:latest
    ports:
      - '${HOST_PORT_FOR_COMPOSE}:80'
    restart: always
    volumes_from:
      - wordpress_with_theme_db:ro
    environment:
      WORDPRESS_DB_HOST: wordpress_with_theme_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
```
below error occur when compose up.
```
Error: (HTTP code 400) unexpected - invalid port specification: "${HOST_PORT_FOR_COMPOSE}" 
```
