### ISSUE TITLE
compose services startet with dockerode-compose did not connect to external docker-networks

### ISSUE THREAD

**Issue by AndreasHeine** [apocas/dockerode-compose#37]
Hey,

i am starting two compose-files with dockerode-compose which behave not the same way like if i started them from commandline.

### service1:
```yaml
version: '3'
services:

  container1:
    hostname: container1
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "8081:1880"
    networks:
      net1: {}

networks:
  net1:
    external: true
    name: transfer
```

### service2:
```yaml
version: '3'
services:

  container2:
    hostname: container2
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "8082:1880"
    networks:
      net1: {}

networks:
  net1:
    external: true
    name: transfer

```

### code:
```ts
const Docker = require('dockerode')
const DockerodeCompose = require('dockerode-compose');

const socketPath = '/var/run/docker.sock'
const docker = new Docker({socketPath: socketPath})

const service1 = new DockerodeCompose(docker, "./service1/docker-compose.yaml", "service1")
const service2 = new DockerodeCompose(docker, "./service2/docker-compose.yaml", "service2")

;(async () => {
    await docker.createNetwork({
        "Name": "transfer"
    })

    await Promise.all([
        service1.up(),
        service2.up()
    ])

})()

;
[
    "uncaughtException",
    "unhandledRejection"
].forEach(event => {
    process.on(event, (...args: any[]) => {
        console.error(`Something went wrong fix your application :P \n`, args)
        process.exit(1)
    })
})
```

### error:
```
Something went wrong fix your application :P 
 [
  Error: (HTTP code 404) no such container - network service1_net1 not found 
      at /home/andreas/Playground/dockerode_compose_test/node_modules/docker-modem/lib/modem.js:343:17
      at getCause (/home/andreas/Playground/dockerode_compose_test/node_modules/docker-modem/lib/modem.js:373:7)
      at Modem.buildPayload (/home/andreas/Playground/dockerode_compose_test/node_modules/docker-modem/lib/modem.js:342:5)
      at IncomingMessage.<anonymous> (/home/andreas/Playground/dockerode_compose_test/node_modules/docker-modem/lib/modem.js:310:16)
      at IncomingMessage.emit (node:events:526:35)
      at IncomingMessage.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    reason: 'no such container',
    statusCode: 404,
    json: { message: 'network service1_net1 not found' }
  },
  Promise {
    <rejected> Error: (HTTP code 404) no such container - network service1_net1 not found 
        at /home/andreas/Playground/dockerode_compose_test/node_modules/docker-modem/lib/modem.js:343:17
        at getCause (/home/andreas/Playground/dockerode_compose_test/node_modules/docker-modem/lib/modem.js:373:7)
        at Modem.buildPayload (/home/andreas/Playground/dockerode_compose_test/node_modules/docker-modem/lib/modem.js:342:5)
        at IncomingMessage.<anonymous> (/home/andreas/Playground/dockerode_compose_test/node_modules/docker-modem/lib/modem.js:310:16)
        at IncomingMessage.emit (node:events:526:35)
        at IncomingMessage.emit (node:domain:489:12)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at processTicksAndRejections (node:internal/process/task_queues:82:21) {
      reason: 'no such container',
      statusCode: 404,
      json: [Object]
    }
  }
]
```

### if i start them from commandline and what i expect to happen:
![Screenshot from 2023-09-20 09-48-49](https://github.com/apocas/dockerode-compose/assets/56362817/b0a62424-94e8-42f0-a20d-e2bbd610181a)

![Screenshot from 2023-09-20 09-49-13](https://github.com/apocas/dockerode-compose/assets/56362817/568b9231-7968-43c5-94e6-9bdf6ff15c41)

## did i use dockerode-compose incorrectly?
