### ISSUE TITLE
Compose.pull() fails when a service doesn't provide an 'image' property

### ISSUE THREAD

**Issue by loriswit** [apocas/dockerode-compose#42]
I have the following compose file:
```yaml
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
```
Running `compose.pull()` triggers the following error:
```
node_modules/dockerode/lib/util.js:48
  var digestPos = input.indexOf('@');
                        ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at module.exports.parseRepositoryTag (node_modules/dockerode/lib/util.js:48:25)
    at Docker.pull (node_modules/dockerode/lib/docker.js:1457:23)
    at Compose.pull (node_modules/dockerode-compose/compose.js:69:41)
```

I suspect this is related to this piece of code: https://github.com/apocas/dockerode-compose/blob/7875946d6b57a0eddcfadfccd4a6aeae187166cd/compose.js#L62-L69

At line 69, the code assumes there's always an `image` property in the service. However, as shown in my compose file, there's no such property in the `web` service.

This should be easily fixable by skipping services that don't provide an image.
