### ISSUE TITLE
Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by ffMathy** [apocas/dockerode-compose#46]
Cannot read properties of undefined (reading 'indexOf')

Here's my docker-compose file:

```yaml
version: '3'

services:
  lucidlink:
    container_name: lucidlink

    build:
      context: ../../
      dockerfile: Dockerfile
      target: lucidlink

    ports:
      - "7778:7778"
```

Init code:

```typescript
const dockerCompose = new DockerodeCompose(this.docker, this.options.dockerComposePath, 'wats-test');
await dockerCompose.pull();
await dockerCompose.up({
  verbose: true
});
```
